<a href="https://colab.research.google.com/github/csslg22/XII-Informatics-Practices-065/blob/main/Boolean%20Indexing%20%26%20Filtering%20-%20Inventory%20DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'ProductID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductName': ['iPhone 15', 'Galaxy S23', 'MacBook Air', 'Dell XPS', 'AirPods',
                    'Sony WH-1000XM5', 'iPad Pro', 'Kindle', 'Apple Watch', 'Gaming Mouse'],
    'Category': ['Mobile', 'Mobile', 'Laptop', 'Laptop', 'Audio', 'Audio', 'Tablet', 'E-Reader', 'Wearable', 'Accessories'],
    'Brand': ['Apple', 'Samsung', 'Apple', 'Dell', 'Apple', 'Sony', 'Apple', 'Amazon', 'Apple', 'Logitech'],
    'Price': [799, 749, 999, 1200, 249, 349, 899, 139, 399, 79],
    'Quantity': [15, 10, 8, 5, 50, 12, 0, 20, 18, 25],
    'Rating': [4.8, 4.5, 4.9, 4.2, 4.7, 4.8, 4.6, 4.4, 4.5, 4.1]
}

inventory_df = pd.DataFrame(data)

In [3]:
df1 = inventory_df.copy()

In [4]:
df1

   ProductID      ProductName     Category     Brand  Price  Quantity  Rating
0        101        iPhone 15       Mobile     Apple    799        15     4.8
1        102       Galaxy S23       Mobile   Samsung    749        10     4.5
2        103      MacBook Air       Laptop     Apple    999         8     4.9
3        104         Dell XPS       Laptop      Dell   1200         5     4.2
4        105          AirPods        Audio     Apple    249        50     4.7
5        106  Sony WH-1000XM5        Audio      Sony    349        12     4.8
6        107         iPad Pro       Tablet     Apple    899         0     4.6
7        108           Kindle     E-Reader    Amazon    139        20     4.4
8        109      Apple Watch     Wearable     Apple    399        18     4.5
9        110     Gaming Mouse  Accessories  Logitech     79        25     4.1

In [5]:
print(df1.head())

   ProductID  ProductName Category    Brand  Price  Quantity  Rating
0        101    iPhone 15   Mobile    Apple    799        15     4.8
1        102   Galaxy S23   Mobile  Samsung    749        10     4.5
2        103  MacBook Air   Laptop    Apple    999         8     4.9
3        104     Dell XPS   Laptop     Dell   1200         5     4.2
4        105      AirPods    Audio    Apple    249        50     4.7

In [6]:
print(df1[df1['Category']=='Mobile'])

   ProductID ProductName Category    Brand  Price  Quantity  Rating
0        101   iPhone 15   Mobile    Apple    799        15     4.8
1        102  Galaxy S23   Mobile  Samsung    749        10     4.5

In [7]:
print(df1[df1['Price']>800])

   ProductID  ProductName Category  Brand  Price  Quantity  Rating
2        103  MacBook Air   Laptop  Apple    999         8     4.9
3        104     Dell XPS   Laptop   Dell   1200         5     4.2
6        107     iPad Pro   Tablet  Apple    899         0     4.6

In [8]:
print(df1.loc[(df1['Quantity']==0), ['ProductName', 'Brand']])

  ProductName  Brand
6    iPad Pro  Apple

In [9]:
print(df1.loc[(df1['Brand'] == 'Apple') & (df1['Price']<500)])

   ProductID  ProductName  Category  Brand  Price  Quantity  Rating
4        105      AirPods     Audio  Apple    249        50     4.7
8        109  Apple Watch  Wearable  Apple    399        18     4.5

In [10]:
print(df1.loc[(df1['Category'] == 'Laptop') | (df1['Category'] == 'Tablet')])

   ProductID  ProductName Category  Brand  Price  Quantity  Rating
2        103  MacBook Air   Laptop  Apple    999         8     4.9
3        104     Dell XPS   Laptop   Dell   1200         5     4.2
6        107     iPad Pro   Tablet  Apple    899         0     4.6

In [11]:
print(df1.loc[(df1['Category'].isin(['Laptop', 'Tablet']))])

   ProductID  ProductName Category  Brand  Price  Quantity  Rating
2        103  MacBook Air   Laptop  Apple    999         8     4.9
3        104     Dell XPS   Laptop   Dell   1200         5     4.2
6        107     iPad Pro   Tablet  Apple    899         0     4.6

In [12]:
print(df1[(df1['Rating']>4.5) & (df1['Price'] < 900)])

   ProductID      ProductName Category  Brand  Price  Quantity  Rating
0        101        iPhone 15   Mobile  Apple    799        15     4.8
4        105          AirPods    Audio  Apple    249        50     4.7
5        106  Sony WH-1000XM5    Audio   Sony    349        12     4.8
6        107         iPad Pro   Tablet  Apple    899         0     4.6

In [13]:
print(df1.loc[~(df1['Brand'] == 'Apple')])

   ProductID      ProductName     Category     Brand  Price  Quantity  Rating
1        102       Galaxy S23       Mobile   Samsung    749        10     4.5
3        104         Dell XPS       Laptop      Dell   1200         5     4.2
5        106  Sony WH-1000XM5        Audio      Sony    349        12     4.8
7        108           Kindle     E-Reader    Amazon    139        20     4.4
9        110     Gaming Mouse  Accessories  Logitech     79        25     4.1

In [14]:
print(df1[df1['ProductName'].str.contains("Watch", case=False)])

   ProductID  ProductName  Category  Brand  Price  Quantity  Rating
8        109  Apple Watch  Wearable  Apple    399        18     4.5

In [15]:
print(df1[df1['Price']>df1['Price'].mean()])

   ProductID  ProductName Category    Brand  Price  Quantity  Rating
0        101    iPhone 15   Mobile    Apple    799        15     4.8
1        102   Galaxy S23   Mobile  Samsung    749        10     4.5
2        103  MacBook Air   Laptop    Apple    999         8     4.9
3        104     Dell XPS   Laptop     Dell   1200         5     4.2
6        107     iPad Pro   Tablet    Apple    899         0     4.6

In [16]:
print(df1[df1['ProductName'].str.startswith("S")])

   ProductID      ProductName Category Brand  Price  Quantity  Rating
5        106  Sony WH-1000XM5    Audio  Sony    349        12     4.8

In [17]:
print(df1[df1['Price'].isin([249,349,799])])

   ProductID      ProductName Category  Brand  Price  Quantity  Rating
0        101        iPhone 15   Mobile  Apple    799        15     4.8
4        105          AirPods    Audio  Apple    249        50     4.7
5        106  Sony WH-1000XM5    Audio   Sony    349        12     4.8

In [18]:
df1

   ProductID      ProductName     Category     Brand  Price  Quantity  Rating
0        101        iPhone 15       Mobile     Apple    799        15     4.8
1        102       Galaxy S23       Mobile   Samsung    749        10     4.5
2        103      MacBook Air       Laptop     Apple    999         8     4.9
3        104         Dell XPS       Laptop      Dell   1200         5     4.2
4        105          AirPods        Audio     Apple    249        50     4.7
5        106  Sony WH-1000XM5        Audio      Sony    349        12     4.8
6        107         iPad Pro       Tablet     Apple    899         0     4.6
7        108           Kindle     E-Reader    Amazon    139        20     4.4
8        109      Apple Watch     Wearable     Apple    399        18     4.5
9        110     Gaming Mouse  Accessories  Logitech     79        25     4.1

In [19]:
df1.loc[df1['Category'] == 'Accessories', 'Quantity'] += 10

In [20]:
df1

   ProductID      ProductName     Category     Brand  Price  Quantity  Rating
0        101        iPhone 15       Mobile     Apple    799        15     4.8
1        102       Galaxy S23       Mobile   Samsung    749        10     4.5
2        103      MacBook Air       Laptop     Apple    999         8     4.9
3        104         Dell XPS       Laptop      Dell   1200         5     4.2
4        105          AirPods        Audio     Apple    249        50     4.7
5        106  Sony WH-1000XM5        Audio      Sony    349        12     4.8
6        107         iPad Pro       Tablet     Apple    899         0     4.6
7        108           Kindle     E-Reader    Amazon    139        20     4.4
8        109      Apple Watch     Wearable     Apple    399        18     4.5
9        110     Gaming Mouse  Accessories  Logitech     79        35     4.1

In [21]:
df1['InventoryValue'] = df1['Price'] * df1['Quantity']
df1

,ProductID,ProductName,Category,Brand,Price,Quantity,Rating,InventoryValue
0,101,iPhone 15,Mobile,Apple,799,15,4.8,11985
1,102,Galaxy S23,Mobile,Samsung,749,10,4.5,7490
2,103,MacBook Air,Laptop,Apple,999,8,4.9,7992
3,104,Dell XPS,Laptop,Dell,1200,5,4.2,6000
4,105,AirPods,Audio,Apple,249,50,4.7,12450
5,106,Sony WH-1000XM5,Audio,Sony,349,12,4.8,4188
6,107,iPad Pro,Tablet,Apple,899,0,4.6,0
7,108,Kindle,E-Reader,Amazon,139,20,4.4,2780
8,109,Apple Watch,Wearable,Apple,399,18,4.5,7182
9,110,Gaming Mouse,Accessories,Logitech,79,35,4.1,2765

In [22]:
df1.loc[df1['Rating'] < 4.3, 'ProductName'] = "Refurbished - " + df1['ProductName']
print(df1)

   ProductID                 ProductName     Category     Brand  Price  \
0        101                   iPhone 15       Mobile     Apple    799
1        102                  Galaxy S23       Mobile   Samsung    749
2        103                 MacBook Air       Laptop     Apple    999
3        104      Refurbished - Dell XPS       Laptop      Dell   1200
4        105                     AirPods        Audio     Apple    249
5        106             Sony WH-1000XM5        Audio      Sony    349
6        107                    iPad Pro       Tablet     Apple    899
7        108                      Kindle     E-Reader    Amazon    139
8        109                 Apple Watch     Wearable     Apple    399
9        110  Refurbished - Gaming Mouse  Accessories  Logitech     79

   Quantity  Rating  InventoryValue
0        15     4.8           11985
1        10     4.5            7490
2         8     4.9            7992
3         5     4.2            6000
4        50     4.7           12450
5        12     4.8            4188
6         0     4.6               0
7        20     4.4            2780
8        18     4.5            7182
9        35     4.1            2765

In [23]:
df1.loc[(df1['Category'] == 'Laptop'),'Price'] = df1['Price'] / 1.10
print(df1)

   ProductID                 ProductName     Category     Brand        Price  \
0        101                   iPhone 15       Mobile     Apple   799.000000
1        102                  Galaxy S23       Mobile   Samsung   749.000000
2        103                 MacBook Air       Laptop     Apple   908.181818
3        104      Refurbished - Dell XPS       Laptop      Dell  1090.909091
4        105                     AirPods        Audio     Apple   249.000000
5        106             Sony WH-1000XM5        Audio      Sony   349.000000
6        107                    iPad Pro       Tablet     Apple   899.000000
7        108                      Kindle     E-Reader    Amazon   139.000000
8        109                 Apple Watch     Wearable     Apple   399.000000
9        110  Refurbished - Gaming Mouse  Accessories  Logitech    79.000000

   Quantity  Rating  InventoryValue
0        15     4.8           11985
1        10     4.5            7490
2         8     4.9            7992
3         5     4.2            6000
4        50     4.7           12450
5        12     4.8            4188
6         0     4.6               0
7        20     4.4            2780
8        18     4.5            7182
9        35     4.1            2765

/tmp/ipykernel_15156/2524743184.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ 908.18181818 1090.90909091]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df1.loc[(df1['Category'] == 'Laptop'),'Price'] = df1['Price'] / 1.10

In [24]:
df1

,ProductID,ProductName,Category,Brand,Price,Quantity,Rating,InventoryValue
0,101,iPhone 15,Mobile,Apple,799.000000,15,4.8,11985
1,102,Galaxy S23,Mobile,Samsung,749.000000,10,4.5,7490
2,103,MacBook Air,Laptop,Apple,908.181818,8,4.9,7992
3,104,Refurbished - Dell XPS,Laptop,Dell,1090.909091,5,4.2,6000
4,105,AirPods,Audio,Apple,249.000000,50,4.7,12450
5,106,Sony WH-1000XM5,Audio,Sony,349.000000,12,4.8,4188
6,107,iPad Pro,Tablet,Apple,899.000000,0,4.6,0
7,108,Kindle,E-Reader,Amazon,139.000000,20,4.4,2780
8,109,Apple Watch,Wearable,Apple,399.000000,18,4.5,7182
9,110,Refurbished - Gaming Mouse,Accessories,Logitech,79.000000,35,4.1,2765

In [25]:
print(df1.groupby("Brand")['Category'].count())

Brand
Amazon      1
Apple       5
Dell        1
Logitech    1
Samsung     1
Sony        1
Name: Category, dtype: int64

In [26]:
print(df1.loc[(df1['Rating'] == df1['Rating'].max()),'ProductName'])

2    MacBook Air
Name: ProductName, dtype: object

In [27]:
df1[df1['InventoryValue']>10000]

,ProductID,ProductName,Category,Brand,Price,Quantity,Rating,InventoryValue
0,101,iPhone 15,Mobile,Apple,799.0,15,4.8,11985
4,105,AirPods,Audio,Apple,249.0,50,4.7,12450

In [28]:
apple_condition = (df1['Brand'] == 'Apple') & (df1['Category'].isin(['Mobile', 'Wearable']))

apple_products = df1[apple_condition]
print(apple_products)

   ProductID  ProductName  Category  Brand  Price  Quantity  Rating  \
0        101    iPhone 15    Mobile  Apple  799.0        15     4.8
8        109  Apple Watch  Wearable  Apple  399.0        18     4.5

   InventoryValue
0           11985
8            7182

In [29]:
import numpy as np

# 1. Define the list of conditions
conditions = [
    (df1['Quantity'] > 20),                                # Condition 1
    (df1['Quantity'] >= 1) & (df1['Quantity'] <= 20), # Condition 2
    (df1['Quantity'] == 0)                                 # Condition 3
]

# 2. Define the corresponding choices for each condition
choices = ['High Stock', 'Available', 'Out of Stock']

# 3. Use np.select to assign the values based on conditions
df1['Status'] = np.select(conditions, choices, default='Unknown')

# Display the updated DataFrame
print(df1[['ProductName', 'Quantity', 'Status']])

                  ProductName  Quantity        Status
0                   iPhone 15        15     Available
1                  Galaxy S23        10     Available
2                 MacBook Air         8     Available
3      Refurbished - Dell XPS         5     Available
4                     AirPods        50    High Stock
5             Sony WH-1000XM5        12     Available
6                    iPad Pro         0  Out of Stock
7                      Kindle        20     Available
8                 Apple Watch        18     Available
9  Refurbished - Gaming Mouse        35    High Stock

In [30]:
df1

,ProductID,ProductName,Category,Brand,Price,Quantity,Rating,InventoryValue,Status
0,101,iPhone 15,Mobile,Apple,799.000000,15,4.8,11985,Available
1,102,Galaxy S23,Mobile,Samsung,749.000000,10,4.5,7490,Available
2,103,MacBook Air,Laptop,Apple,908.181818,8,4.9,7992,Available
3,104,Refurbished - Dell XPS,Laptop,Dell,1090.909091,5,4.2,6000,Available
4,105,AirPods,Audio,Apple,249.000000,50,4.7,12450,High Stock
5,106,Sony WH-1000XM5,Audio,Sony,349.000000,12,4.8,4188,Available
6,107,iPad Pro,Tablet,Apple,899.000000,0,4.6,0,Out of Stock
7,108,Kindle,E-Reader,Amazon,139.000000,20,4.4,2780,Available
8,109,Apple Watch,Wearable,Apple,399.000000,18,4.5,7182,Available
9,110,Refurbished - Gaming Mouse,Accessories,Logitech,79.000000,35,4.1,2765,High Stock