<a href="https://colab.research.google.com/github/csslg22/XII-Informatics-Practices-065/blob/main/DataFrame%2002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
s = pd.Series([10,20,30,40,50,60,70,80,90,100])
print(s)

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64

In [ ]:
print(s>70)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8     True
9     True
dtype: bool

In [ ]:
print(s[s>70])

7     80
8     90
9    100
dtype: int64

# Boolean Indexing and Filtering in DataFrame

In [ ]:
import numpy as np
data = {
    'Name'  : ['Amit', 'Bhavna', 'Deepa', 'Esha'],
    'Marks' : [45, 85, 92, 55]
}
df = pd.DataFrame(data)

In [ ]:
print(df)

     Name  Marks
0    Amit     45
1  Bhavna     85
2   Deepa     92
3    Esha     55

In [ ]:
print(df['Marks']>80) # Gives us a Boolean Series output

0    False
1     True
2     True
3    False
Name: Marks, dtype: bool

In [ ]:
print(df[df['Marks']>80]) # Gives us the actual values which satisfy the condition

     Name  Marks
1  Bhavna     85
2   Deepa     92

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Name'     : ['Amit','Bhavna','Chintu','Deepa','Esha',
                   'Faisal','Gaurav','Hina','Ishan','Sara','Ravi'],
    'Class'    : [11, 12, 11, 11, 12, 11, 12, 11, 12, 12, 11],
    'Section'  : ['A','B','A','C','A','B','A','B','C','A','C'],
    'Marks'    : [45, 85, 30, 92, 55, 62, 78, 25, 48, 95, 60],
    'Physics'  : [50, 80, 20, 95, 60, 65, 80, 30, 40, 90, 55],
    'Chemistry': [40, 85, 35, 90, 50, 70, 75, 20, 55, 92, 65],
    'English'  : [60, 75, 40, 88, 65, 55, 85, 45, 60, 89, 70],
    'Remarks'  : ['Average','Good','Poor','Excellent','Average',
                   'Average','Good','Poor','Average','Excellent','Average']
}
df = pd.DataFrame(data)

In [ ]:
print(df)

      Name  Class Section  Marks  Physics  Chemistry  English    Remarks
0     Amit     11       A     45       50         40       60    Average
1   Bhavna     12       B     85       80         85       75       Good
2   Chintu     11       A     30       20         35       40       Poor
3    Deepa     11       C     92       95         90       88  Excellent
4     Esha     12       A     55       60         50       65    Average
5   Faisal     11       B     62       65         70       55    Average
6   Gaurav     12       A     78       80         75       85       Good
7     Hina     11       B     25       30         20       45       Poor
8    Ishan     12       C     48       40         55       60    Average
9     Sara     12       A     95       90         92       89  Excellent
10    Ravi     11       C     60       55         65       70    Average

In [ ]:
df

      Name  Class Section  Marks  Physics  Chemistry  English    Remarks
0     Amit     11       A     45       50         40       60    Average
1   Bhavna     12       B     85       80         85       75       Good
2   Chintu     11       A     30       20         35       40       Poor
3    Deepa     11       C     92       95         90       88  Excellent
4     Esha     12       A     55       60         50       65    Average
5   Faisal     11       B     62       65         70       55    Average
6   Gaurav     12       A     78       80         75       85       Good
7     Hina     11       B     25       30         20       45       Poor
8    Ishan     12       C     48       40         55       60    Average
9     Sara     12       A     95       90         92       89  Excellent
10    Ravi     11       C     60       55         65       70    Average

In [ ]:
print(df[df['Marks']>80])

     Name  Class Section  Marks  Physics  Chemistry  English    Remarks
1  Bhavna     12       B     85       80         85       75       Good
3   Deepa     11       C     92       95         90       88  Excellent
9    Sara     12       A     95       90         92       89  Excellent

In [ ]:
print(df[df['Physics']<60])

      Name  Class Section  Marks  Physics  Chemistry  English  Remarks
0     Amit     11       A     45       50         40       60  Average
2   Chintu     11       A     30       20         35       40     Poor
7     Hina     11       B     25       30         20       45     Poor
8    Ishan     12       C     48       40         55       60  Average
10    Ravi     11       C     60       55         65       70  Average

In [ ]:
print(df[(df['Chemistry']>=50) & (df['Chemistry']<=70)])

      Name  Class Section  Marks  Physics  Chemistry  English  Remarks
4     Esha     12       A     55       60         50       65  Average
5   Faisal     11       B     62       65         70       55  Average
8    Ishan     12       C     48       40         55       60  Average
10    Ravi     11       C     60       55         65       70  Average

In [ ]:
print(df[df['Remarks']=='Poor'])

     Name  Class Section  Marks  Physics  Chemistry  English Remarks
2  Chintu     11       A     30       20         35       40    Poor
7    Hina     11       B     25       30         20       45    Poor

In [ ]:
print(df[(df['Class']==12) & (df['Section']=='C')])

    Name  Class Section  Marks  Physics  Chemistry  English  Remarks
8  Ishan     12       C     48       40         55       60  Average

In [ ]:
print(df[(df['Class']==11) | (df['Section']=='C')])

      Name  Class Section  Marks  Physics  Chemistry  English    Remarks
0     Amit     11       A     45       50         40       60    Average
2   Chintu     11       A     30       20         35       40       Poor
3    Deepa     11       C     92       95         90       88  Excellent
5   Faisal     11       B     62       65         70       55    Average
7     Hina     11       B     25       30         20       45       Poor
8    Ishan     12       C     48       40         55       60    Average
10    Ravi     11       C     60       55         65       70    Average

In [ ]:
print(df[~(df['Class'] == 11)])

     Name  Class Section  Marks  Physics  Chemistry  English    Remarks
1  Bhavna     12       B     85       80         85       75       Good
4    Esha     12       A     55       60         50       65    Average
6  Gaurav     12       A     78       80         75       85       Good
8   Ishan     12       C     48       40         55       60    Average
9    Sara     12       A     95       90         92       89  Excellent

In [ ]:
print(df.shape)

(11, 8)

In [ ]:
# Display the Name, Class and Section of those students whose marks >= 75
print(df.loc[(df['Marks']>=75),['Name','Class','Section']])

     Name  Class Section
1  Bhavna     12       B
3   Deepa     11       C
6  Gaurav     12       A
9    Sara     12       A

In [ ]:
print(df.loc[(df['Marks']>=75),'Name'])

1    Bhavna
3     Deepa
6    Gaurav
9      Sara
Name: Name, dtype: object

In [ ]:
# Display the name and marks of Physics of those students whose Remarks is Average

print(df.loc[(df['Remarks']=='Average'),['Name', 'Physics']])

      Name  Physics
0     Amit       50
4     Esha       60
5   Faisal       65
8    Ishan       40
10    Ravi       55

In [ ]:
print(df.loc[(df['Remarks']=='Average'),:])

      Name  Class Section  Marks  Physics  Chemistry  English  Remarks
0     Amit     11       A     45       50         40       60  Average
4     Esha     12       A     55       60         50       65  Average
5   Faisal     11       B     62       65         70       55  Average
8    Ishan     12       C     48       40         55       60  Average
10    Ravi     11       C     60       55         65       70  Average

In [ ]:
# Display the name, class and section of those students whose marks in Physics is greater than 70 and Marks in English is greater than 50.

print(df.loc[(df['Physics']>70) & (df['English']>50),['Name','Class','Section']])

     Name  Class Section
1  Bhavna     12       B
3   Deepa     11       C
6  Gaurav     12       A
9    Sara     12       A

In [ ]:
# Display the name and remarks of those students whose section is not B

print(df.loc[(df['Section']!='B'),['Name','Section','Remarks']])

      Name Section    Remarks
0     Amit       A    Average
2   Chintu       A       Poor
3    Deepa       C  Excellent
4     Esha       A    Average
6   Gaurav       A       Good
8    Ishan       C    Average
9     Sara       A  Excellent
10    Ravi       C    Average

In [ ]:
print(df.loc[~(df['Section']=='B'),['Name','Section','Remarks']])

      Name Section    Remarks
0     Amit       A    Average
2   Chintu       A       Poor
3    Deepa       C  Excellent
4     Esha       A    Average
6   Gaurav       A       Good
8    Ishan       C    Average
9     Sara       A  Excellent
10    Ravi       C    Average

In [ ]:
print(df.describe())

           Class      Marks    Physics  Chemistry    English
count  11.000000  11.000000  11.000000  11.000000  11.000000
mean   11.454545  61.363636  60.454545  61.545455  66.545455
std     0.522233  23.875815  24.439164  23.712291  16.669515
min    11.000000  25.000000  20.000000  20.000000  40.000000
25%    11.000000  46.500000  45.000000  45.000000  57.500000
50%    11.000000  60.000000  60.000000  65.000000  65.000000
75%    12.000000  81.500000  80.000000  80.000000  80.000000
max    12.000000  95.000000  95.000000  92.000000  89.000000

In [ ]:
# print(df['Chemistry'].max())
max_chemistry = df['Chemistry'].max()

In [ ]:
print(max_chemistry)

92

In [ ]:
print(df.loc[df['Chemistry']==max_chemistry,['Name']])

   Name
9  Sara

In [ ]:
print(df.loc[df['Chemistry']==df['Chemistry'].min(),['Name']])

   Name
7  Hina

In [ ]:
print(df.columns)

Index(['Name', 'Class', 'Section', 'Marks', 'Physics', 'Chemistry', 'English',
       'Remarks'],
      dtype='object')

**Practice Questions 15.05.2026**

1. Display all students who scored more than 60 in English.

In [ ]:
print(df[df['English']>60])

      Name  Class Section  Marks  Physics  Chemistry  English    Remarks
1   Bhavna     12       B     85       80         85       75       Good
3    Deepa     11       C     92       95         90       88  Excellent
4     Esha     12       A     55       60         50       65    Average
6   Gaurav     12       A     78       80         75       85       Good
9     Sara     12       A     95       90         92       89  Excellent
10    Ravi     11       C     60       55         65       70    Average

2. Show names of students in Class 12 who scored above 80 in Marks.

In [ ]:
print(df.loc[(df['Class']==12) & (df['Marks']>80)])

     Name  Class Section  Marks  Physics  Chemistry  English    Remarks
1  Bhavna     12       B     85       80         85       75       Good
9    Sara     12       A     95       90         92       89  Excellent

3. Display records of students who are either in Section A or scored above 90 in
Physics.

In [ ]:
print(df.loc[(df['Section']=='A') | (df['Physics']>90)])
# print(df.loc[(df['Section']=='A') | (df['Physics']>90),:]) - This is also correct form of writing

     Name  Class Section  Marks  Physics  Chemistry  English    Remarks
0    Amit     11       A     45       50         40       60    Average
2  Chintu     11       A     30       20         35       40       Poor
3   Deepa     11       C     92       95         90       88  Excellent
4    Esha     12       A     55       60         50       65    Average
6  Gaurav     12       A     78       80         75       85       Good
9    Sara     12       A     95       90         92       89  Excellent

4. Show Name and Remarks of students who are NOT in Class 11.

In [ ]:
print(df.loc[~(df['Class']==11),['Name','Remarks']])
# print(df.loc[(df['Class']!=11),['Name','Remarks']])

     Name    Remarks
1  Bhavna       Good
4    Esha    Average
6  Gaurav       Good
8   Ishan    Average
9    Sara  Excellent

5. Display Name and Chemistry marks of the student with the highest Physics marks.

In [ ]:
phy = df['Physics'].max()
print(df.loc[(df['Physics']==phy),['Name','Chemistry']])

    Name  Chemistry
3  Deepa         90

6. Display all students with Marks between 50 and 80 (both inclusive).

In [ ]:
print(df[(df['Marks']>=50) & (df['Marks']<=80)])

      Name  Class Section  Marks  Physics  Chemistry  English  Remarks
4     Esha     12       A     55       60         50       65  Average
5   Faisal     11       B     62       65         70       55  Average
6   Gaurav     12       A     78       80         75       85     Good
10    Ravi     11       C     60       55         65       70  Average

In [ ]:
print(df[df['Marks'].between(50,80)])

      Name  Class Section  Marks  Physics  Chemistry  English  Remarks
4     Esha     12       A     55       60         50       65  Average
5   Faisal     11       B     62       65         70       55  Average
6   Gaurav     12       A     78       80         75       85     Good
10    Ravi     11       C     60       55         65       70  Average

In [ ]:
df

      Name  Class Section  Marks  Physics  Chemistry  English    Remarks
0     Amit     11       A     45       50         40       60    Average
1   Bhavna     12       B     85       80         85       75       Good
2   Chintu     11       A     30       20         35       40       Poor
3    Deepa     11       C     92       95         90       88  Excellent
4     Esha     12       A     55       60         50       65    Average
5   Faisal     11       B     62       65         70       55    Average
6   Gaurav     12       A     78       80         75       85       Good
7     Hina     11       B     25       30         20       45       Poor
8    Ishan     12       C     48       40         55       60    Average
9     Sara     12       A     95       90         92       89  Excellent
10    Ravi     11       C     60       55         65       70    Average

In [ ]:
# Create a new column named 'Total' storing the sum of Physics, Chemistry and English.

df['Total'] = df['Physics'] + df['Chemistry'] + df['English']
print(df)

      Name  Class Section  Marks  Physics  Chemistry  English    Remarks  \
0     Amit     11       A     45       50         40       60    Average
1   Bhavna     12       B     85       80         85       75       Good
2   Chintu     11       A     30       20         35       40       Poor
3    Deepa     11       C     92       95         90       88  Excellent
4     Esha     12       A     55       60         50       65    Average
5   Faisal     11       B     62       65         70       55    Average
6   Gaurav     12       A     78       80         75       85       Good
7     Hina     11       B     25       30         20       45       Poor
8    Ishan     12       C     48       40         55       60    Average
9     Sara     12       A     95       90         92       89  Excellent
10    Ravi     11       C     60       55         65       70    Average

    Total
0     150
1     240
2      95
3     273
4     175
5     190
6     240
7      95
8     155
9     271
10    190

In [ ]:
mean_total = df['Total'].mean()

In [ ]:
# Display the names of those students whose total is more than the mean value.
print(df.loc[(df['Total']>mean_total),'Name'])

1     Bhavna
3      Deepa
5     Faisal
6     Gaurav
9       Sara
10      Ravi
Name: Name, dtype: object

In [ ]:
df

,Name,Class,Section,Marks,Physics,Chemistry,English,Remarks,Total
0,Amit,11,A,45,50,40,60,Average,150
1,Bhavna,12,B,85,80,85,75,Good,240
2,Chintu,11,A,30,20,35,40,Poor,95
3,Deepa,11,C,92,95,90,88,Excellent,273
4,Esha,12,A,55,60,50,65,Average,175
5,Faisal,11,B,62,65,70,55,Average,190
6,Gaurav,12,A,78,80,75,85,Good,240
7,Hina,11,B,25,30,20,45,Poor,95
8,Ishan,12,C,48,40,55,60,Average,155
9,Sara,12,A,95,90,92,89,Excellent,271
10,Ravi,11,C,60,55,65,70,Average,190

In [ ]:
# Increase the marks by 5 for those whose Marks is less than or equal to 50.
print(df.loc[(df['Marks']<=50), ['Name', 'Class', 'Section', 'Marks']])

     Name  Class Section  Marks
0    Amit     11       A     45
2  Chintu     11       A     30
7    Hina     11       B     25
8   Ishan     12       C     48

In [ ]:
df.loc[(df['Marks']<=50), 'Marks'] += 5
print(df.loc[(df['Marks']<=50), ['Name', 'Class', 'Section', 'Marks']])

     Name  Class Section  Marks
0    Amit     11       A     50
2  Chintu     11       A     35
7    Hina     11       B     30

In [ ]:
# Change the sections to C1 of those students studying in class 11 C.
print(df.loc[(df['Section']=='C') & (df['Class'] == 11)])

     Name  Class Section  Marks  Physics  Chemistry  English    Remarks  Total
3   Deepa     11       C     92       95         90       88  Excellent    273
10   Ravi     11       C     60       55         65       70    Average    190

In [ ]:
df.loc[(df['Section']=='C') & (df['Class'] == 11),'Section'] = 'C1'
print(df.loc[(df['Section']=='C1') & (df['Class'] == 11)])

     Name  Class Section  Marks  Physics  Chemistry  English    Remarks  Total
3   Deepa     11      C1     92       95         90       88  Excellent    273
10   Ravi     11      C1     60       55         65       70    Average    190

In [ ]:
# Update the Remarks to 'Good' for students whose Marks is above 75.
print(df.loc[(df['Marks']>75)])
df.loc[(df['Marks']>75),'Remarks'] = 'Good'
print(df.loc[(df['Marks']>75)])

     Name  Class Section  Marks  Physics  Chemistry  English    Remarks  Total
1  Bhavna     12       B     85       80         85       75       Good    240
3   Deepa     11      C1     92       95         90       88  Excellent    273
6  Gaurav     12       A     78       80         75       85       Good    240
9    Sara     12       A     95       90         92       89  Excellent    271
     Name  Class Section  Marks  Physics  Chemistry  English Remarks  Total
1  Bhavna     12       B     85       80         85       75    Good    240
3   Deepa     11      C1     92       95         90       88    Good    273
6  Gaurav     12       A     78       80         75       85    Good    240
9    Sara     12       A     95       90         92       89    Good    271

In [ ]:
df

      Name  Class Section  Marks  Physics  Chemistry  English  Remarks  Total
0     Amit     11       A     50       50         40       60  Average    150
1   Bhavna     12       B     85       80         85       75     Good    240
2   Chintu     11       A     35       20         35       40     Poor     95
3    Deepa     11      C1     92       95         90       88     Good    273
4     Esha     12       A     55       60         50       65  Average    175
5   Faisal     11       B     62       65         70       55  Average    190
6   Gaurav     12       A     78       80         75       85     Good    240
7     Hina     11       B     30       30         20       45     Poor     95
8    Ishan     12       C     53       40         55       60  Average    155
9     Sara     12       A     95       90         92       89     Good    271
10    Ravi     11      C1     60       55         65       70  Average    190

In [ ]:
df['Marks'].nlargest(3)

9    95
3    92
1    85
Name: Marks, dtype: int64

In [ ]:
print(df.loc[df['Marks'].isin(df['Marks'].nlargest(3)),['Name','Class','Section']])

     Name  Class Section
1  Bhavna     12       B
3   Deepa     11      C1
9    Sara     12       A

In [110]:
inventory_df

   ProductID      ProductName     Category     Brand  Price  Quantity  Rating
0        101        iPhone 15       Mobile     Apple    799        15     4.8
1        102       Galaxy S23       Mobile   Samsung    749        10     4.5
2        103      MacBook Air       Laptop     Apple    999         8     4.9
3        104         Dell XPS       Laptop      Dell   1200         5     4.2
4        105          AirPods        Audio     Apple    249        50     4.7
5        106  Sony WH-1000XM5        Audio      Sony    349        12     4.8
6        107         iPad Pro       Tablet     Apple    899         0     4.6
7        108           Kindle     E-Reader    Amazon    139        20     4.4
8        109      Apple Watch     Wearable     Apple    399        18     4.5
9        110     Gaming Mouse  Accessories  Logitech     79        25     4.1

In [111]:
df1 = inventory_df.copy()

In [112]:
df1

   ProductID      ProductName     Category     Brand  Price  Quantity  Rating
0        101        iPhone 15       Mobile     Apple    799        15     4.8
1        102       Galaxy S23       Mobile   Samsung    749        10     4.5
2        103      MacBook Air       Laptop     Apple    999         8     4.9
3        104         Dell XPS       Laptop      Dell   1200         5     4.2
4        105          AirPods        Audio     Apple    249        50     4.7
5        106  Sony WH-1000XM5        Audio      Sony    349        12     4.8
6        107         iPad Pro       Tablet     Apple    899         0     4.6
7        108           Kindle     E-Reader    Amazon    139        20     4.4
8        109      Apple Watch     Wearable     Apple    399        18     4.5
9        110     Gaming Mouse  Accessories  Logitech     79        25     4.1

In [113]:
print(df1.head())

   ProductID  ProductName Category    Brand  Price  Quantity  Rating
0        101    iPhone 15   Mobile    Apple    799        15     4.8
1        102   Galaxy S23   Mobile  Samsung    749        10     4.5
2        103  MacBook Air   Laptop    Apple    999         8     4.9
3        104     Dell XPS   Laptop     Dell   1200         5     4.2
4        105      AirPods    Audio    Apple    249        50     4.7

In [114]:
print(df1[df1['Category']=='Mobile'])

   ProductID ProductName Category    Brand  Price  Quantity  Rating
0        101   iPhone 15   Mobile    Apple    799        15     4.8
1        102  Galaxy S23   Mobile  Samsung    749        10     4.5

In [115]:
print(df1[df1['Price']>800])

   ProductID  ProductName Category  Brand  Price  Quantity  Rating
2        103  MacBook Air   Laptop  Apple    999         8     4.9
3        104     Dell XPS   Laptop   Dell   1200         5     4.2
6        107     iPad Pro   Tablet  Apple    899         0     4.6

In [116]:
print(df1.loc[(df1['Quantity']==0), ['ProductName', 'Brand']])

  ProductName  Brand
6    iPad Pro  Apple

In [117]:
print(df1.loc[(df1['Brand'] == 'Apple') & (df1['Price']<500)])

   ProductID  ProductName  Category  Brand  Price  Quantity  Rating
4        105      AirPods     Audio  Apple    249        50     4.7
8        109  Apple Watch  Wearable  Apple    399        18     4.5

In [118]:
print(df1.loc[(df1['Category'] == 'Laptop') | (df1['Category'] == 'Tablet')])

   ProductID  ProductName Category  Brand  Price  Quantity  Rating
2        103  MacBook Air   Laptop  Apple    999         8     4.9
3        104     Dell XPS   Laptop   Dell   1200         5     4.2
6        107     iPad Pro   Tablet  Apple    899         0     4.6

In [119]:
print(df1.loc[(df1['Category'].isin(['Laptop', 'Tablet']))])

   ProductID  ProductName Category  Brand  Price  Quantity  Rating
2        103  MacBook Air   Laptop  Apple    999         8     4.9
3        104     Dell XPS   Laptop   Dell   1200         5     4.2
6        107     iPad Pro   Tablet  Apple    899         0     4.6

In [120]:
print(df1[(df1['Rating']>4.5) & (df1['Price'] < 900)])

   ProductID      ProductName Category  Brand  Price  Quantity  Rating
0        101        iPhone 15   Mobile  Apple    799        15     4.8
4        105          AirPods    Audio  Apple    249        50     4.7
5        106  Sony WH-1000XM5    Audio   Sony    349        12     4.8
6        107         iPad Pro   Tablet  Apple    899         0     4.6

In [121]:
print(df1.loc[~(df1['Brand'] == 'Apple')])

   ProductID      ProductName     Category     Brand  Price  Quantity  Rating
1        102       Galaxy S23       Mobile   Samsung    749        10     4.5
3        104         Dell XPS       Laptop      Dell   1200         5     4.2
5        106  Sony WH-1000XM5        Audio      Sony    349        12     4.8
7        108           Kindle     E-Reader    Amazon    139        20     4.4
9        110     Gaming Mouse  Accessories  Logitech     79        25     4.1

In [122]:
print(df1[df1['ProductName'].str.contains("Watch", case=False)])

   ProductID  ProductName  Category  Brand  Price  Quantity  Rating
8        109  Apple Watch  Wearable  Apple    399        18     4.5

In [123]:
print(df1[df1['Price']>df1['Price'].mean()])

   ProductID  ProductName Category    Brand  Price  Quantity  Rating
0        101    iPhone 15   Mobile    Apple    799        15     4.8
1        102   Galaxy S23   Mobile  Samsung    749        10     4.5
2        103  MacBook Air   Laptop    Apple    999         8     4.9
3        104     Dell XPS   Laptop     Dell   1200         5     4.2
6        107     iPad Pro   Tablet    Apple    899         0     4.6

In [124]:
print(df1[df1['ProductName'].str.startswith("S")])

   ProductID      ProductName Category Brand  Price  Quantity  Rating
5        106  Sony WH-1000XM5    Audio  Sony    349        12     4.8

In [125]:
print(df1[df1['Price'].isin([249,349,799])])

   ProductID      ProductName Category  Brand  Price  Quantity  Rating
0        101        iPhone 15   Mobile  Apple    799        15     4.8
4        105          AirPods    Audio  Apple    249        50     4.7
5        106  Sony WH-1000XM5    Audio   Sony    349        12     4.8

In [126]:
df1

   ProductID      ProductName     Category     Brand  Price  Quantity  Rating
0        101        iPhone 15       Mobile     Apple    799        15     4.8
1        102       Galaxy S23       Mobile   Samsung    749        10     4.5
2        103      MacBook Air       Laptop     Apple    999         8     4.9
3        104         Dell XPS       Laptop      Dell   1200         5     4.2
4        105          AirPods        Audio     Apple    249        50     4.7
5        106  Sony WH-1000XM5        Audio      Sony    349        12     4.8
6        107         iPad Pro       Tablet     Apple    899         0     4.6
7        108           Kindle     E-Reader    Amazon    139        20     4.4
8        109      Apple Watch     Wearable     Apple    399        18     4.5
9        110     Gaming Mouse  Accessories  Logitech     79        25     4.1

In [127]:
df1.loc[df1['Category'] == 'Accessories', 'Quantity'] += 10

In [128]:
df1

   ProductID      ProductName     Category     Brand  Price  Quantity  Rating
0        101        iPhone 15       Mobile     Apple    799        15     4.8
1        102       Galaxy S23       Mobile   Samsung    749        10     4.5
2        103      MacBook Air       Laptop     Apple    999         8     4.9
3        104         Dell XPS       Laptop      Dell   1200         5     4.2
4        105          AirPods        Audio     Apple    249        50     4.7
5        106  Sony WH-1000XM5        Audio      Sony    349        12     4.8
6        107         iPad Pro       Tablet     Apple    899         0     4.6
7        108           Kindle     E-Reader    Amazon    139        20     4.4
8        109      Apple Watch     Wearable     Apple    399        18     4.5
9        110     Gaming Mouse  Accessories  Logitech     79        35     4.1

In [129]:
df1['InventoryValue'] = df1['Price'] * df1['Quantity']
df1

,ProductID,ProductName,Category,Brand,Price,Quantity,Rating,InventoryValue
0,101,iPhone 15,Mobile,Apple,799,15,4.8,11985
1,102,Galaxy S23,Mobile,Samsung,749,10,4.5,7490
2,103,MacBook Air,Laptop,Apple,999,8,4.9,7992
3,104,Dell XPS,Laptop,Dell,1200,5,4.2,6000
4,105,AirPods,Audio,Apple,249,50,4.7,12450
5,106,Sony WH-1000XM5,Audio,Sony,349,12,4.8,4188
6,107,iPad Pro,Tablet,Apple,899,0,4.6,0
7,108,Kindle,E-Reader,Amazon,139,20,4.4,2780
8,109,Apple Watch,Wearable,Apple,399,18,4.5,7182
9,110,Gaming Mouse,Accessories,Logitech,79,35,4.1,2765

In [130]:
df1.loc[df1['Rating'] < 4.3, 'ProductName'] = "Refurbished - " + df1['ProductName']
print(df1)

,ProductID,ProductName,Category,Brand,Price,Quantity,Rating,InventoryValue
0,101,iPhone 15,Mobile,Apple,799,15,4.8,11985
1,102,Galaxy S23,Mobile,Samsung,749,10,4.5,7490
2,103,MacBook Air,Laptop,Apple,999,8,4.9,7992
3,104,Refurbished - Dell XPS,Laptop,Dell,1200,5,4.2,6000
4,105,AirPods,Audio,Apple,249,50,4.7,12450
5,106,Sony WH-1000XM5,Audio,Sony,349,12,4.8,4188
6,107,iPad Pro,Tablet,Apple,899,0,4.6,0
7,108,Kindle,E-Reader,Amazon,139,20,4.4,2780
8,109,Apple Watch,Wearable,Apple,399,18,4.5,7182
9,110,Refurbished - Gaming Mouse,Accessories,Logitech,79,35,4.1,2765

In [132]:
df1.loc[(df1['Category'] == 'Laptop'),'Price'] = df1['Price'] / 1.10
print(df1)

,ProductID,ProductName,Category,Brand,Price,Quantity,Rating,InventoryValue
0,101,iPhone 15,Mobile,Apple,799.000000,15,4.8,11985
1,102,Galaxy S23,Mobile,Samsung,749.000000,10,4.5,7490
2,103,MacBook Air,Laptop,Apple,825.619835,8,4.9,7992
3,104,Refurbished - Dell XPS,Laptop,Dell,991.735537,5,4.2,6000
4,105,AirPods,Audio,Apple,249.000000,50,4.7,12450
5,106,Sony WH-1000XM5,Audio,Sony,349.000000,12,4.8,4188
6,107,iPad Pro,Tablet,Apple,899.000000,0,4.6,0
7,108,Kindle,E-Reader,Amazon,139.000000,20,4.4,2780
8,109,Apple Watch,Wearable,Apple,399.000000,18,4.5,7182
9,110,Refurbished - Gaming Mouse,Accessories,Logitech,79.000000,35,4.1,2765