In [1]:
import pandas as pd
import numpy as np
# pd.DataFrame(data, index, columns, dtype, copy)

In [2]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [3]:
df1 = pd.DataFrame([1,2,3,4,5])
print(df1)

   0
0  1
1  2
2  3
3  4
4  5

In [4]:
data = [['Freya', 10], ['Mohak', 12], ['Dwivedi', 13]]
df2 = pd.DataFrame(data, columns=['Name', 'Age'])
print(df2)

      Name  Age
0    Freya   10
1    Mohak   12
2  Dwivedi   13

In [5]:
# Explicitly specifying the dtype while DataFrame creation
df3 = pd.DataFrame([11,22,33], dtype=float)
print(df3)

      0
0  11.0
1  22.0
2  33.0

In [6]:
# Creating DataFrame from Dictionary of ndarray/Lists
data = {'Name': ['Freya', 'Mohak', 'Dwivedi'], 'Age': np.array([10, 12, 13])}
df4 = pd.DataFrame(data, index=['S1', 'S2', 'S3'])
print(df4)

       Name  Age
S1    Freya   10
S2    Mohak   12
S3  Dwivedi   13

In [7]:
# Creating DataFrame from List of Dictionaries

data1 = [{'x':1, 'y':2}, {'x':5, 'y':4, 'z':5}]
df1 = pd.DataFrame(data1, index=["R1", "R2"])
print(df1)

    x  y    z
R1  1  2  NaN
R2  5  4  5.0

In [8]:
# Creating a DataFrame from Dictionary of Series
d1 = {'one': pd.Series([1,2,3], index=['a', 'b', 'c']),
      'two': pd.Series([1,2,3,4], index=['a', 'b', 'c', 'd'])}
df5 = pd.DataFrame(d1)
print(df5)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [9]:
# Adding a new column - passing as a Series
df5['three'] = pd.Series([10,20,30], index=['a','b','c'])
print(df5)

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

In [10]:
# Adding a new column using existing column values
df5['four'] = df5['one'] + df5['three']
print(df5)

   one  two  three  four
a  1.0    1   10.0  11.0
b  2.0    2   20.0  22.0
c  3.0    3   30.0  33.0
d  NaN    4    NaN   NaN

In [11]:
## Creating a DataFrame using a CSV file
# df6 = pd.read_csv('data1.csv')
# print(df6)

In [12]:
# Changing the index from system-defined to user-defined
# df61 = pd.read_csv('data1.csv',index_col=0) # 0 indicates first column
# print(df61)

In [13]:
# Changing the header row from first row to some other row
# df62 = pd.read_csv('data1.csv', header=1) # 1 indicates the 2nd row
# print(df62)

# Addition of Data into a DataFrame

Consider a DataFrame `Marks`

In [14]:
import pandas as pd
data = {'Name':['Ram', 'Sonu', 'Rita'],
        'Eng':[25,23,24],
        'Maths':[29,27,26]}
Marks = pd.DataFrame(data)
print(Marks)

   Name  Eng  Maths
0   Ram   25     29
1  Sonu   23     27
2  Rita   24     26

In [15]:
# Add a new column
Marks['IP'] = [29,28,27]
print(Marks)

   Name  Eng  Maths  IP
0   Ram   25     29  29
1  Sonu   23     27  28
2  Rita   24     26  27

In [16]:
Marks['Eng'] = 30
print(Marks)

   Name  Eng  Maths  IP
0   Ram   30     29  29
1  Sonu   30     27  28
2  Rita   30     26  27

Here, `Eng` is a column which already exists in the DataFrame `Marks`.

If we put a scalar value for an already existing column, Python will update the entire column with the new value, as seen in the example.

If, we give a column name which does not exist in the DataFrame, then Python will create a new column with similar value set for all the rows.

Example: `Marks['CS'] = 29` will add a new column CS with value 29 set for all the rows.

In [17]:
print(len(Marks))

3

In [18]:
Marks.loc[len(Marks)] = ['Dinesh', 29, 28, 27]
print(Marks)
# OR
# Marks[len(Marks)] = ['Dinesh', 29, 28, 27]
#print(Marks)

     Name  Eng  Maths  IP
0     Ram   30     29  29
1    Sonu   30     27  28
2    Rita   30     26  27
3  Dinesh   29     28  27

If we give an index value which does not exist, Python will insert the new row in that index position. If we give an index which already exists, Python will update the existing row.

Example:

In [19]:
Marks.loc[3] = ['Shyam', 21, 22, 23]
print(Marks)

    Name  Eng  Maths  IP
0    Ram   30     29  29
1   Sonu   30     27  28
2   Rita   30     26  27
3  Shyam   21     22  23

# Accessing Values from a DataFrame

Using `loc` and `iloc`

**Syntax:**

`df.loc[rowstart:rowend, colstart:colend]`

`df.iloc[rowindexstart:rowindexend, colindexstart:colindexend]`

In [20]:
print(Marks)
# Let us consider the following DataFrame:

    Name  Eng  Maths  IP
0    Ram   30     29  29
1   Sonu   30     27  28
2   Rita   30     26  27
3  Shyam   21     22  23

In [21]:

print(Marks.loc[:,'Name'])

0      Ram
1     Sonu
2     Rita
3    Shyam
Name: Name, dtype: object

In [22]:
print(Marks['Name'])

0      Ram
1     Sonu
2     Rita
3    Shyam
Name: Name, dtype: object

In [23]:
print(Marks.iloc[:,0])

0      Ram
1     Sonu
2     Rita
3    Shyam
Name: Name, dtype: object

In [24]:
# print(Marks.loc[:,0])
# This will raise Error if columns are already labelled.

Whenever we extract a single column from a DataFrame, the data type of the output is a **Pandas Series**.

In [25]:
print(Marks[['Name','Maths']])

    Name  Maths
0    Ram     29
1   Sonu     27
2   Rita     26
3  Shyam     22

In [26]:
print(Marks.loc[:,['Name', 'Maths']])

    Name  Maths
0    Ram     29
1   Sonu     27
2   Rita     26
3  Shyam     22

In [27]:
print(Marks.loc[:,'Name':'Maths'])

    Name  Eng  Maths
0    Ram   30     29
1   Sonu   30     27
2   Rita   30     26
3  Shyam   21     22

In [28]:
print(Marks.iloc[:,0:3])

    Name  Eng  Maths
0    Ram   30     29
1   Sonu   30     27
2   Rita   30     26
3  Shyam   21     22

In [29]:
Marks

    Name  Eng  Maths  IP
0    Ram   30     29  29
1   Sonu   30     27  28
2   Rita   30     26  27
3  Shyam   21     22  23

Accessing Single Row

In [30]:
print(Marks.loc[2])

Name     Rita
Eng        30
Maths      26
IP         27
Name: 2, dtype: object

In [31]:
print(type(Marks.loc[2]))

<class 'pandas.core.series.Series'>

In [32]:
print(Marks.loc[1:3])

    Name  Eng  Maths  IP
1   Sonu   30     27  28
2   Rita   30     26  27
3  Shyam   21     22  23

In [33]:
print(Marks.iloc[1:4])

    Name  Eng  Maths  IP
1   Sonu   30     27  28
2   Rita   30     26  27
3  Shyam   21     22  23

In [34]:
print(Marks.loc[1:3,'Eng':'IP'])

   Eng  Maths  IP
1   30     27  28
2   30     26  27
3   21     22  23

In [35]:
print(Marks.iloc[1:3,1:3])

   Eng  Maths
1   30     27
2   30     26

# Deletion of values from DataFrame

In [36]:
# Labelled DataFrame
d = {'Name':['Amit', 'Riya', 'Sohan', 'Neha'],
     'Marks':[85,90,78,92],
     'City':['Delhi', 'Mumbai', 'Pune', 'Kolkata']}
df = pd.DataFrame(d, index=['a', 'b', 'c', 'd'])

In [37]:
print(df)

    Name  Marks     City
a   Amit     85    Delhi
b   Riya     90   Mumbai
c  Sohan     78     Pune
d   Neha     92  Kolkata

In [38]:
# Unlabelled DataFrame
data = [['Amit',85,'Delhi'],['Riya',90,'Mumbai'],['Sohan',78,'Pune'],['Neha',92,'Kolkata']]
df2 = pd.DataFrame(data)
print(df2)

       0   1        2
0   Amit  85    Delhi
1   Riya  90   Mumbai
2  Sohan  78     Pune
3   Neha  92  Kolkata

`axis=0`, `axis=1`

`inplace=True`, `inplace=False`

In [39]:
# Deletion
# 1. Single Row Deletion (Labelled):
df.drop('b') # This is temporary deletion

    Name  Marks     City
a   Amit     85    Delhi
c  Sohan     78     Pune
d   Neha     92  Kolkata

In [40]:
print(df)

    Name  Marks     City
a   Amit     85    Delhi
b   Riya     90   Mumbai
c  Sohan     78     Pune
d   Neha     92  Kolkata

In [41]:
# Single row deletion (labelled)
df.drop('b', inplace=True)

In [42]:
print(df)

    Name  Marks     City
a   Amit     85    Delhi
c  Sohan     78     Pune
d   Neha     92  Kolkata

In [43]:
# Multiple row deletion (labelled)
df.drop(['a','c'], inplace=True)
print(df)

   Name  Marks     City
d  Neha     92  Kolkata

In [44]:
# Single row deletion (unlabelled)
df2.drop(1,inplace=True)
print(df2)

       0   1        2
0   Amit  85    Delhi
2  Sohan  78     Pune
3   Neha  92  Kolkata

In [45]:
# Multiple row deletion (unlabelled)
df2.drop([0,2],inplace=True)
print(df2)

      0   1        2
3  Neha  92  Kolkata

In [46]:
print("Labelled DataFrame df\n")
print(df)
print("UnLabelled DataFrame df2\n")
print(df2)

Labelled DataFrame df

   Name  Marks     City
d  Neha     92  Kolkata
UnLabelled DataFrame df2

      0   1        2
3  Neha  92  Kolkata

In [47]:
# Column deletion
# Single Column Deletion (labelled)
df.drop('City',axis=1,inplace=True)
print(df)

   Name  Marks
d  Neha     92

In [48]:
# Multiple Column Deletion (labelled)
df.drop(['Name','Marks'],axis=1,inplace=True)
print(df)

Empty DataFrame
Columns: []
Index: [d]

In [49]:
# Single column deletion (unlabelled)
print(df2)

      0   1        2
3  Neha  92  Kolkata

In [50]:
df2.drop(2,axis=1)

      0   1
3  Neha  92

In [51]:
df3 = df2.drop(2,axis=1)
print(df3)

      0   1
3  Neha  92

In [52]:
df2

      0   1        2
3  Neha  92  Kolkata

In [53]:
# Single column deletion (unlabelled)
df2.drop(2,axis=1,inplace=True)

In [54]:
print(df2)

      0   1
3  Neha  92

In [55]:
# Multiple column deletion (unlabelled)
df2.drop([0,1],axis=1,inplace=True)
print(df2)

Empty DataFrame
Columns: []
Index: [3]

`head()` and `tail()` functions in DataFrame

In [56]:
data = {'Col1':[x for x in range(10,20,1)],
        'Col2':[x for x in range(20,30,1)]}
df4 = pd.DataFrame(data,index=['R1','R2','R3','R4','R5','R6','R7','R8','R9','R10'])
print(df4)

     Col1  Col2
R1     10    20
R2     11    21
R3     12    22
R4     13    23
R5     14    24
R6     15    25
R7     16    26
R8     17    27
R9     18    28
R10    19    29

In [57]:
df4.head()

    Col1  Col2
R1    10    20
R2    11    21
R3    12    22
R4    13    23
R5    14    24

In [58]:
df4.tail()

     Col1  Col2
R6     15    25
R7     16    26
R8     17    27
R9     18    28
R10    19    29

In [59]:
df4.tail(3)

     Col1  Col2
R8     17    27
R9     18    28
R10    19    29

In [60]:
df4.head(2)

    Col1  Col2
R1    10    20
R2    11    21

# Attributes of DataFrame

In [61]:
data = {'Roll':[101,102,103],
        'Name':['Amit','Bina','Chirag'],
        'Marks':[85,92,78]}
df = pd.DataFrame(data,index=['R1','R2','R3'])
print(df)

    Roll    Name  Marks
R1   101    Amit     85
R2   102    Bina     92
R3   103  Chirag     78

In [62]:
# Display the index of the DataFrame
print("Index:",df.index)

Index: Index(['R1', 'R2', 'R3'], dtype='object')

In [63]:
# Display the columns of the DataFrame
print("Columns:",df.columns)

Columns: Index(['Roll', 'Name', 'Marks'], dtype='object')

In [64]:
# Display the axes values of the DataFrame
print("Axes:",df.axes)

Axes: [Index(['R1', 'R2', 'R3'], dtype='object'), Index(['Roll', 'Name', 'Marks'], dtype='object')]

In [65]:
# Display the dimension of the DataFrame
print("Dimension:",df.ndim)

Dimension: 2

In [66]:
# Display the shape of the DataFrame
print("Shape:",df.shape)

Shape: (3, 3)

In [67]:
# Display the size of the DataFrame
print("Size:",df.size)

Size: 9

In [68]:
df

    Roll    Name  Marks
R1   101    Amit     85
R2   102    Bina     92
R3   103  Chirag     78

In [92]:
print(df.dtypes) # It gives the datatypes of all the columns
# Each individual column of the DataFrame is a Series in itself.

Roll      int64
Name     object
Marks     int64
dtype: object

In [70]:
print(df['Roll'])

R1    101
R2    102
R3    103
Name: Roll, dtype: int64

In [71]:
print(type(df['Roll']))

<class 'pandas.core.series.Series'>

In [72]:
print(df['Roll'].dtype) # It gives the datatype of one individual column.

int64

In [73]:
# Check if DataFrame is empty or not
print(df.empty)

False

In [74]:
df

    Roll    Name  Marks
R1   101    Amit     85
R2   102    Bina     92
R3   103  Chirag     78

In [75]:
# Values of the DataFrame
print(df.values)

[[101 'Amit' 85]
 [102 'Bina' 92]
 [103 'Chirag' 78]]

In [76]:
df2 = pd.DataFrame(df.values)
print(df2)

     0       1   2
0  101    Amit  85
1  102    Bina  92
2  103  Chirag  78

In [77]:
print("Memory Location of df:",id(df))
print("Memory Location of df2:",id(df2))

Memory Location of df: 132388242621840
Memory Location of df2: 132388242337152

In [78]:
df2[3] = ['A', 'A+', 'B']
print(df2)

     0       1   2   3
0  101    Amit  85   A
1  102    Bina  92  A+
2  103  Chirag  78   B

In [79]:
# Transpose a DataFrame
print(df2.T)

      0     1       2
0   101   102     103
1  Amit  Bina  Chirag
2    85    92      78
3     A    A+       B

# Renaming rows & columns of a DataFrame

In [80]:
# Let us consider the following DataFrames df1 & df2:

d1 = {'RollNo':[101,102,103],
      'Name':['Abhi','Shyam', 'Ronit']}
d2 = [[121, 'Anand'],
      [122, 'Mohit']]
df1 = pd.DataFrame(d1,index=['A1','A2','A3'])
df2 = pd.DataFrame(d2)
print("DataFrame df1:")
print(df1)
print("-"*20)
print("DataFrame df2:")
print(df2)

DataFrame df1:
    RollNo   Name
A1     101   Abhi
A2     102  Shyam
A3     103  Ronit
--------------------
DataFrame df2:
     0      1
0  121  Anand
1  122  Mohit

In [81]:
# Rename single column of a labelled DataFrame
df1.rename(columns={'RollNo':'RegNo'},inplace=True)
print(df1)

    RegNo   Name
A1    101   Abhi
A2    102  Shyam
A3    103  Ronit

In [82]:
# Renaming multiple columns in a labelled DataFrame
df1.rename(columns={'RegNo':'RollNo','Name':'StuName'},inplace=True)
print(df1)

    RollNo StuName
A1     101    Abhi
A2     102   Shyam
A3     103   Ronit

In [83]:
# Renaming Single Row in a labelled DataFrame
df1.rename(index={'A1':'A21'},inplace=True)
print(df1)

     RollNo StuName
A21     101    Abhi
A2      102   Shyam
A3      103   Ronit

In [84]:
# Renaming multiple row in a labelled DataFrame
df1.rename(index={'A2':'A22','A3':'A23'},inplace=True)
print(df1)

     RollNo StuName
A21     101    Abhi
A22     102   Shyam
A23     103   Ronit

In [85]:
print(df2)

     0      1
0  121  Anand
1  122  Mohit

In [86]:
# Renaming system-assigned column names to user-defined column names
# Process is similar for single/multiple columns
df2.rename(columns={0:'RegNo',1:'CustName'},inplace=True)
print(df2)

   RegNo CustName
0    121    Anand
1    122    Mohit

In [87]:
# Renaming system-assigned index values to user-defined index values.
# Process is similar for single/multiple indices.
df2.rename(index={0:'C1',1:'C2'},inplace=True)
print(df2)

    RegNo CustName
C1    121    Anand
C2    122    Mohit

# Iterations in a DataFrame

In [88]:
df1

     RollNo StuName
A21     101    Abhi
A22     102   Shyam
A23     103   Ronit

In [89]:
for element in df1:
    print(element)

RollNo
StuName

In [90]:
# Iteration over rows
for row_index, row_value in df1.iterrows():
    print(row_index)
    print('-'*10)
    print(row_value)

A21
----------
RollNo      101
StuName    Abhi
Name: A21, dtype: object
A22
----------
RollNo       102
StuName    Shyam
Name: A22, dtype: object
A23
----------
RollNo       103
StuName    Ronit
Name: A23, dtype: object

In [91]:
# Iteration over columns
for col_index, col_value in df1.items():
    print(col_index)
    print('-'*10)
    print(col_value)

RollNo
----------
A21    101
A22    102
A23    103
Name: RollNo, dtype: int64
StuName
----------
A21     Abhi
A22    Shyam
A23    Ronit
Name: StuName, dtype: object