# DataFrame - II

25-05-2026

In [1]:
import pandas as pd
import numpy as np
marksUT= {'Name':['Raman','Raman','Raman','Zuhaire','Zuhaire','Zuhaire', 'Ashravy','Ashravy','Ashravy','Mishti','Mishti','Mishti'], 'UT':[1,2,3,1,2,3,1,2,3,1,2,3], 'Maths':[22,21,14,20,23,22,23,24,12,15,18,17], 'Science':[21,20,19,17,15,18,19,22,25,22,21,18], 'S.St':[18,17,15,22,21,19,20,24,19,25,25,20],
    'Hindi':[20,22,24,24,25,23,15,17,21,22,24,25], 'Eng':[21,24,23,19,15,13,22,21,23,22,23,20]
}
df=pd.DataFrame(marksUT)
print(df)

       Name  UT  Maths  Science  S.St  Hindi  Eng
0     Raman   1     22       21    18     20   21
1     Raman   2     21       20    17     22   24
2     Raman   3     14       19    15     24   23
3   Zuhaire   1     20       17    22     24   19
4   Zuhaire   2     23       15    21     25   15
5   Zuhaire   3     22       18    19     23   13
6   Ashravy   1     23       19    20     15   22
7   Ashravy   2     24       22    24     17   21
8   Ashravy   3     12       25    19     21   23
9    Mishti   1     15       22    25     22   22
10   Mishti   2     18       21    25     24   23
11   Mishti   3     17       18    20     25   20

In [2]:
print(df['Maths'])

0     22
1     21
2     14
3     20
4     23
5     22
6     23
7     24
8     12
9     15
10    18
11    17
Name: Maths, dtype: int64

In [3]:
print(df.Hindi)

0     20
1     22
2     24
3     24
4     25
5     23
6     15
7     17
8     21
9     22
10    24
11    25
Name: Hindi, dtype: int64

## Descriptive Statistics

`DataFrame.max()` is used to calculate the maximum
values from the DataFrame, regardless of its data types.

In [4]:
print(df.max())

Name       Zuhaire
UT               3
Maths           24
Science         25
S.St            25
Hindi           25
Eng             24
dtype: object

If we want to output maximum value for the columns
having only numeric values, then we can set the
parameter `numeric_only=True` in the `max()` method.

In [5]:
print(df.max(numeric_only=True))

UT          3
Maths      24
Science    25
S.St       25
Hindi      25
Eng        24
dtype: int64

Write the statements to output the
maximum marks obtained in each subject
in Unit Test 2.

In [6]:
dfUT2 = df[df.UT == 2]

In [7]:
print(dfUT2)

       Name  UT  Maths  Science  S.St  Hindi  Eng
1     Raman   2     21       20    17     22   24
4   Zuhaire   2     23       15    21     25   15
7   Ashravy   2     24       22    24     17   21
10   Mishti   2     18       21    25     24   23

In [8]:
print('\nMaximum Mark obtained in Each Subject in Unit Test 2: \n\n',dfUT2.max(numeric_only=True))

Maximum Mark obtained in Each Subject in Unit Test 2:

 UT          2
Maths      24
Science    22
S.St       25
Hindi      25
Eng        24
dtype: int64

By default, the `max()` method finds the maximum
value of each column (which means, `axis=0`). However,
to find the maximum value of each row, we have to
specify `axis = 1` as its argument.

In [9]:
print(dfUT2.iloc[:,1:].max(axis=1))

1     24
4     25
7     24
10    25
dtype: int64

In [10]:
df.iloc[:,1:].max(axis=1)

0     22
1     24
2     24
3     24
4     25
5     23
6     23
7     24
8     25
9     25
10    25
11    25
dtype: int64

In most of the python function calls, `axis = 0` refers
to row wise operations and `axis = 1` refers to column wise
operations. But in the call of `max()`, `axis = 1` gives row wise
output and `axis = 0` (default case) gives column-wise output.

In [11]:
print(df.min())

Name       Ashravy
UT               1
Maths           12
Science         15
S.St            15
Hindi           15
Eng             13
dtype: object

Write the statements to display the
maximum & minimum marks obtained by a particular
student ‘Mishti’ in all the unit tests for
each subject.

In [12]:
dfMishti = df.loc[df.Name == 'Mishti']
print('Marks obtained by Mishti in all the Unit Tests: ',dfMishti,sep="\n")

Marks obtained by Mishti in all the Unit Tests:
      Name  UT  Maths  Science  S.St  Hindi  Eng
9   Mishti   1     15       22    25     22   22
10  Mishti   2     18       21    25     24   23
11  Mishti   3     17       18    20     25   20

In [13]:
print('Maximum Marks obtained by Mishti in each subject across the unit tests:', dfMishti[['Maths','Science','S.St','Hindi','Eng']].max(),sep="\n")

Maximum Marks obtained by Mishti in each subject across the unit tests:
Maths      18
Science    22
S.St       25
Hindi      25
Eng        23
dtype: int64

In [14]:
print('Minimum Marks obtained by Mishti in each subject across the unit tests:', dfMishti[['Maths','Science','S.St','Hindi','Eng']].min(),sep="\n")

Minimum Marks obtained by Mishti in each subject across the unit tests:
Maths      15
Science    18
S.St       20
Hindi      22
Eng        20
dtype: int64

In [15]:
dfMishti

      Name  UT  Maths  Science  S.St  Hindi  Eng
9   Mishti   1     15       22    25     22   22
10  Mishti   2     18       21    25     24   23
11  Mishti   3     17       18    20     25   20

In [16]:
# Maximum marks obtained in each unit test, irrespective of the subject
print(dfMishti[['Maths','Science','S.St','Hindi','Eng']].max(axis=1))

9     25
10    25
11    25
dtype: int64

In [17]:
# Minimum marks obtained in each unit test, irrespective of the subject
print(dfMishti[['Maths','Science','S.St','Hindi','Eng']].min(axis=1))

9     15
10    18
11    17
dtype: int64

In [18]:
dfMishti

      Name  UT  Maths  Science  S.St  Hindi  Eng
9   Mishti   1     15       22    25     22   22
10  Mishti   2     18       21    25     24   23
11  Mishti   3     17       18    20     25   20

In [19]:
dfMishti.loc[(dfMishti['UT']==1),'Maths':].max(axis=1)

9    25
dtype: int64

In [20]:
print(df.sum()) # Column-wise sum of all values

Name       RamanRamanRamanZuhaireZuhaireZuhaireAshravyAsh...
UT                                                        24
Maths                                                    231
Science                                                  237
S.St                                                     245
Hindi                                                    262
Eng                                                      246
dtype: object

In [21]:
print(df['Maths'].sum())

231

In [22]:
print(df.iloc[:,1:].sum(axis=1)) # Row-wise sum of all values

0     103
1     106
2      98
3     103
4     101
5      98
6     100
7     110
8     103
9     107
10    113
11    103
dtype: int64

Write the python statement to print
the total marks secured by Raman in
each subject.

In [23]:
dfRaman=df[df['Name']=='Raman']
print("Marks obtained by Raman in each test are:", dfRaman,sep="\n")

Marks obtained by Raman in each test are:
    Name  UT  Maths  Science  S.St  Hindi  Eng
0  Raman   1     22       21    18     20   21
1  Raman   2     21       20    17     22   24
2  Raman   3     14       19    15     24   23

In [24]:
print(dfRaman[['Maths','Science','S.St','Hindi','Eng']].sum())

Maths      57
Science    60
S.St       50
Hindi      66
Eng        68
dtype: int64

To print total marks scored by Raman in all subjects in each Unit Test

In [25]:
dfRaman[['Maths','Science','S.St','Hindi','Eng']].sum(axis=1)

0    102
1    104
2     95
dtype: int64

In [26]:
print(df.count())

Name       12
UT         12
Maths      12
Science    12
S.St       12
Hindi      12
Eng        12
dtype: int64

Write a statement to count the number of values in a row.

In [27]:
df.count(axis=1)

0     7
1     7
2     7
3     7
4     7
5     7
6     7
7     7
8     7
9     7
10    7
11    7
dtype: int64

In [28]:
# It is only applicable for numeric values.
df.iloc[:,1:].mean()

UT          2.000000
Maths      19.250000
Science    19.750000
S.St       20.416667
Hindi      21.833333
Eng        20.500000
dtype: float64

Write the statements to get an average
of marks obtained by Zuhaire in all the
Unit Tests.

In [29]:
dfZuhaireMarks = df.loc[(df['Name']=='Zuhaire'),'Maths':'Eng']
print("Slicing of the DataFrame to get only the marks", dfZuhaireMarks,sep="\n")

Slicing of the DataFrame to get only the marks
   Maths  Science  S.St  Hindi  Eng
3     20       17    22     24   19
4     23       15    21     25   15
5     22       18    19     23   13

In [30]:
print("Average of marks obtained by Zuhaire in all Unit Tests:",dfZuhaireMarks.mean(axis=1),sep="\n")

Average of marks obtained by Zuhaire in all Unit Tests:
3    20.4
4    19.8
5    19.0
dtype: float64

In [31]:
print(df.iloc[:,1:].median())

UT          2.0
Maths      20.5
Science    19.5
S.St       20.0
Hindi      22.5
Eng        21.5
dtype: float64

Write the statements to print the median
marks of mathematics in UT1.

In [32]:
dfMaths=df['Maths']
dfMathsUT1=dfMaths[df.UT==1]
print("Displaying the marks scored in Mathematics in UT1",dfMathsUT1,sep="\n")

Displaying the marks scored in Mathematics in UT1
0    22
3    20
6    23
9    15
Name: Maths, dtype: int64

In [33]:
dfMathMedian=dfMathsUT1.median()
print("Displaying the median of Mathematics in UT1",dfMathMedian,sep="\n")

Displaying the median of Mathematics in UT1
21.0

In [34]:
print(df['Maths'].median())

20.5

In [35]:
print(df['Hindi'].mode())

0    24
Name: Hindi, dtype: int64

In [36]:
df.iloc[:,1:].quantile() # by default, median is the output

UT          2.0
Maths      20.5
Science    19.5
S.St       20.0
Hindi      22.5
Eng        21.5
Name: 0.5, dtype: float64

In [37]:
print(df.iloc[:,1:].quantile(q=.25))

UT          1.00
Maths      16.50
Science    18.00
S.St       18.75
Hindi      20.75
Eng        19.75
Name: 0.25, dtype: float64

In [38]:
print(df.iloc[:,1:].quantile(q=.50))

UT          2.0
Maths      20.5
Science    19.5
S.St       20.0
Hindi      22.5
Eng        21.5
Name: 0.5, dtype: float64

In [39]:
print(df.iloc[:,1:].quantile(q=.75))

UT          3.00
Maths      22.25
Science    21.25
S.St       22.50
Hindi      24.00
Eng        23.00
Name: 0.75, dtype: float64

Write the statement to display the first and
third quartiles of all subjects.

In [40]:
dfSubject=df[['Maths','Science','S.St','Hindi','Eng']]
print("Marks of all the subjects:",dfSubject,sep="\n")

Marks of all the subjects:
    Maths  Science  S.St  Hindi  Eng
0      22       21    18     20   21
1      21       20    17     22   24
2      14       19    15     24   23
3      20       17    22     24   19
4      23       15    21     25   15
5      22       18    19     23   13
6      23       19    20     15   22
7      24       22    24     17   21
8      12       25    19     21   23
9      15       22    25     22   22
10     18       21    25     24   23
11     17       18    20     25   20

In [41]:
dfQ=dfSubject.quantile([.25,.75])
print("First and third quartiles of all the subjects:",dfQ,sep="\n")

First and third quartiles of all the subjects:
      Maths  Science   S.St  Hindi    Eng
0.25  16.50    18.00  18.75  20.75  19.75
0.75  22.25    21.25  22.50  24.00  23.00

`DataFrame.var()` is used to display the variance. It is the
average of squared differences from the mean.

In [42]:
print(df[['Maths','Science','S.St','Hindi','Eng']].var())

Maths      15.840909
Science     7.113636
S.St        9.901515
Hindi       9.969697
Eng        11.363636
dtype: float64

`DataFrame.std()` returns the standard deviation of the
values. Standard deviation is calculated as the square
root of the variance.

In [43]:
print(df[['Maths','Science','S.St','Hindi','Eng']].std())

Maths      3.980064
Science    2.667140
S.St       3.146667
Hindi      3.157483
Eng        3.370999
dtype: float64

`DataFrame.describe()` function displays the
descriptive statistical values in a single command. These
values help us describe a set of data in a DataFrame.

In [44]:
print(df.describe())

              UT      Maths   Science       S.St      Hindi        Eng
count  12.000000  12.000000  12.00000  12.000000  12.000000  12.000000
mean    2.000000  19.250000  19.75000  20.416667  21.833333  20.500000
std     0.852803   3.980064   2.66714   3.146667   3.157483   3.370999
min     1.000000  12.000000  15.00000  15.000000  15.000000  13.000000
25%     1.000000  16.500000  18.00000  18.750000  20.750000  19.750000
50%     2.000000  20.500000  19.50000  20.000000  22.500000  21.500000
75%     3.000000  22.250000  21.25000  22.500000  24.000000  23.000000
max     3.000000  24.000000  25.00000  25.000000  25.000000  24.000000

## Data Aggregations

Aggregation means to transform the dataset and produce
a single numeric value from an array. Aggregation can
be applied to one or more columns together. Aggregate
functions are `max(),min(), sum(), count(), std(), var()`.

In [45]:
print(df.aggregate('max'))

Name       Zuhaire
UT               3
Maths           24
Science         25
S.St            25
Hindi           25
Eng             24
dtype: object

In [46]:
# #To use multiple aggregate functions in a single statement
print(df.aggregate(['max','count']))

          Name  UT  Maths  Science  S.St  Hindi  Eng
max    Zuhaire   3     24       25    25     25   24
count       12  12     12       12    12     12   12

In [47]:
df.describe()

              UT      Maths   Science       S.St      Hindi        Eng
count  12.000000  12.000000  12.00000  12.000000  12.000000  12.000000
mean    2.000000  19.250000  19.75000  20.416667  21.833333  20.500000
std     0.852803   3.980064   2.66714   3.146667   3.157483   3.370999
min     1.000000  12.000000  15.00000  15.000000  15.000000  13.000000
25%     1.000000  16.500000  18.00000  18.750000  20.750000  19.750000
50%     2.000000  20.500000  19.50000  20.000000  22.500000  21.500000
75%     3.000000  22.250000  21.25000  22.500000  24.000000  23.000000
max     3.000000  24.000000  25.00000  25.000000  25.000000  24.000000

In [48]:
print(df['Maths'].aggregate(['max','min','std']))

max    24.000000
min    12.000000
std     3.980064
Name: Maths, dtype: float64

Note: We can also use the parameter axis with
aggregate function. By default, the value of axis is zero,
means columns.

In [49]:
#Using the above statement with axis=0 gives the same result
print(df['Maths'].aggregate(['max','min'],axis=0))

max    24
min    12
Name: Maths, dtype: int64

In [50]:
#Total marks of Maths and Science obtained by each student.
#Use sum() with axis=1 (Row-wise summation)
print(df[['Maths','Science']].aggregate('sum',axis=1))

0     43
1     41
2     33
3     37
4     38
5     40
6     42
7     46
8     37
9     37
10    39
11    35
dtype: int64

## Sorting a DataFrame

`DataFrame.sort_values(by, axis=0, ascending=True)`

Here, a column list (by), axis arguments (0 for rows
and 1 for columns) and the order of sorting (`ascending
= False or True`) are passed as arguments. By default,
sorting is done on row indexes in ascending order.

In [51]:
#By default, sorting is done in ascending order.
print(df.sort_values(by=['Name']))

       Name  UT  Maths  Science  S.St  Hindi  Eng
6   Ashravy   1     23       19    20     15   22
7   Ashravy   2     24       22    24     17   21
8   Ashravy   3     12       25    19     21   23
9    Mishti   1     15       22    25     22   22
10   Mishti   2     18       21    25     24   23
11   Mishti   3     17       18    20     25   20
0     Raman   1     22       21    18     20   21
1     Raman   2     21       20    17     22   24
2     Raman   3     14       19    15     24   23
3   Zuhaire   1     20       17    22     24   19
4   Zuhaire   2     23       15    21     25   15
5   Zuhaire   3     22       18    19     23   13

In [52]:
# Get the data corresponding to Unit Test 2
dfUT2 = df[df.UT == 2]
# Sort according to ascending order of marks in Science
print(dfUT2.sort_values(by=['Science']))

       Name  UT  Maths  Science  S.St  Hindi  Eng
4   Zuhaire   2     23       15    21     25   15
1     Raman   2     21       20    17     22   24
10   Mishti   2     18       21    25     24   23
7   Ashravy   2     24       22    24     17   21

Write the statement which will sort the
marks in English in the DataFrame df
based on Unit Test 3, in descending order.

In [53]:
dfUT3 = df[df.UT == 3]
# Sort according to descending order of marks in Science
print(dfUT3.sort_values(by=['Eng'],ascending=False))

       Name  UT  Maths  Science  S.St  Hindi  Eng
2     Raman   3     14       19    15     24   23
8   Ashravy   3     12       25    19     21   23
11   Mishti   3     17       18    20     25   20
5   Zuhaire   3     22       18    19     23   13

A DataFrame can be sorted based on multiple
columns. Following is the code of sorting the DataFrame
df based on marks in Science in Unit Test 3 in ascending
order. If marks in Science are the same, then sorting
will be done on the basis of marks in Hindi.

In [54]:
# Get the data corresponding to marks in Unit Test 3
dfUT3 = df[df.UT == 3]
# Sort the data according to Science and then according to Hindi
print(dfUT3.sort_values(by=['Science','Hindi'], ascending=True))

       Name  UT  Maths  Science  S.St  Hindi  Eng
5   Zuhaire   3     22       18    19     23   13
11   Mishti   3     17       18    20     25   20
2     Raman   3     14       19    15     24   23
8   Ashravy   3     12       25    19     21   23

In [55]:
# Descending order
print(dfUT3.sort_values(by=['Science','Hindi'], ascending=False))

       Name  UT  Maths  Science  S.St  Hindi  Eng
8   Ashravy   3     12       25    19     21   23
2     Raman   3     14       19    15     24   23
11   Mishti   3     17       18    20     25   20
5   Zuhaire   3     22       18    19     23   13

Here, we can see that the list is sorted on the basis
of marks in Science. Two students namely, Zuhaire and
Mishti have equal marks (18) in Science. Therefore for
them, sorting is done on the basis of marks in Hindi.

## Group by Functions

In [56]:
#Create a GROUP BY Name of the student from DataFrame df
g1=df.groupby('Name')
#Displaying the first entry from each group
print(g1.first())

         UT  Maths  Science  S.St  Hindi  Eng
Name
Ashravy   1     23       19    20     15   22
Mishti    1     15       22    25     22   22
Raman     1     22       21    18     20   21
Zuhaire   1     20       17    22     24   19

In [57]:
#Displaying the size of each group
print(g1.size())

Name
Ashravy    3
Mishti     3
Raman      3
Zuhaire    3
dtype: int64

In [58]:
'''
Displaying group data, i.e., group_name, row indexes corresponding to the group and their data type
'''

print(g1.groups)

{'Ashravy': [6, 7, 8], 'Mishti': [9, 10, 11], 'Raman': [0, 1, 2], 'Zuhaire': [3, 4, 5]}

In [59]:
#Printing data of a single group
print(g1.get_group('Raman'))

    Name  UT  Maths  Science  S.St  Hindi  Eng
0  Raman   1     22       21    18     20   21
1  Raman   2     21       20    17     22   24
2  Raman   3     14       19    15     24   23

In [60]:
#Grouping with respect to multiple attributes
#Creating a GROUP BY Name and UT
g2=df.groupby(['Name', 'UT'])
print(g2.first())

            Maths  Science  S.St  Hindi  Eng
Name    UT
Ashravy 1      23       19    20     15   22
        2      24       22    24     17   21
        3      12       25    19     21   23
Mishti  1      15       22    25     22   22
        2      18       21    25     24   23
        3      17       18    20     25   20
Raman   1      22       21    18     20   21
        2      21       20    17     22   24
        3      14       19    15     24   23
Zuhaire 1      20       17    22     24   19
        2      23       15    21     25   15
        3      22       18    19     23   13

The above statements show how we create groups by
splitting a DataFrame using `groupby()`. Next step is
to apply functions over the groups just created. This is
done using Aggregation.

Aggregation is a process in which an aggregate function is applied on each group created by `groupby()`. It returns a single aggregated statistical value
corresponding to each group. It can be used to apply multiple functions over an axis. Be default, functions are applied over columns. Aggregation can be performed using `agg()` or `aggregate()` function.

In [61]:
#Calculating average marks scored by all students in each subject for each UT
print(df.iloc[:,1:].groupby(['UT']).aggregate('mean'))

    Maths  Science   S.St  Hindi    Eng
UT
1   20.00    19.75  21.25  20.25  21.00
2   21.50    19.50  21.75  22.00  20.75
3   16.25    20.00  18.25  23.25  19.75

In [62]:
# Calculate average marks scored in Maths in each UT
group1=df.groupby(['UT'])
print(group1['Maths'].aggregate('mean'))

UT
1    20.00
2    21.50
3    16.25
Name: Maths, dtype: float64

Write the python statements to print the
mean, variance, standard deviation and
quartile of the marks scored in Mathematics
by each student across the UTs.

In [63]:
print(df.groupby(by='Name')['Maths'].agg(['mean','var','std','quantile']))

              mean        var       std  quantile
Name
Ashravy  19.666667  44.333333  6.658328      23.0
Mishti   16.666667   2.333333  1.527525      17.0
Raman    19.000000  19.000000  4.358899      21.0
Zuhaire  21.666667   2.333333  1.527525      22.0

## Handling missing values

In [64]:
marksUT = {
'Name':['Raman','Raman','Raman','Raman','Zuhaire','Zuhaire','Zuhaire'
,'Zuhaire','Ashravy','Ashravy','Ashravy','Ashravy','Mishti','Mishti',
'Mishti','Mishti'],
'UT':[1,2,3,4,1,2,3,4,1,2,3,4,1,2,3,4],
'Maths':[22,21,14,np.nan,20,23,22,19,23,24,12,15,15,18,17,14],
'Science':[21,20,19,np.nan,17,15,18,20,19,22,25,20,22,21,18,20],
'S.St':[18,17,15,19,22,21,19,17,20,24,19,20,25,25,20,19],
'Hindi':[20,22,24,18,24,25,23,21, 15,17,21,20,22,24,25,20],
'Eng':[21,24,23,np.nan,19,15,13,16,22,21,23,17,22,23,20,18] }
df = pd.DataFrame(marksUT)
print(df)

       Name  UT  Maths  Science  S.St  Hindi   Eng
0     Raman   1   22.0     21.0    18     20  21.0
1     Raman   2   21.0     20.0    17     22  24.0
2     Raman   3   14.0     19.0    15     24  23.0
3     Raman   4    NaN      NaN    19     18   NaN
4   Zuhaire   1   20.0     17.0    22     24  19.0
5   Zuhaire   2   23.0     15.0    21     25  15.0
6   Zuhaire   3   22.0     18.0    19     23  13.0
7   Zuhaire   4   19.0     20.0    17     21  16.0
8   Ashravy   1   23.0     19.0    20     15  22.0
9   Ashravy   2   24.0     22.0    24     17  21.0
10  Ashravy   3   12.0     25.0    19     21  23.0
11  Ashravy   4   15.0     20.0    20     20  17.0
12   Mishti   1   15.0     22.0    25     22  22.0
13   Mishti   2   18.0     21.0    25     24  23.0
14   Mishti   3   17.0     18.0    20     25  20.0
15   Mishti   4   14.0     20.0    19     20  18.0

In [65]:
print(df.isnull())

     Name     UT  Maths  Science   S.St  Hindi    Eng
0   False  False  False    False  False  False  False
1   False  False  False    False  False  False  False
2   False  False  False    False  False  False  False
3   False  False   True     True  False  False   True
4   False  False  False    False  False  False  False
5   False  False  False    False  False  False  False
6   False  False  False    False  False  False  False
7   False  False  False    False  False  False  False
8   False  False  False    False  False  False  False
9   False  False  False    False  False  False  False
10  False  False  False    False  False  False  False
11  False  False  False    False  False  False  False
12  False  False  False    False  False  False  False
13  False  False  False    False  False  False  False
14  False  False  False    False  False  False  False
15  False  False  False    False  False  False  False

The following statement checks whether attribute
‘Science’ has a missing value or not. It returns True for
each row where there is a missing value for attribute
‘Science’, and False otherwise.

In [66]:
print(df['Science'].isnull())

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
Name: Science, dtype: bool

In [67]:
print(df.isnull().any())

Name       False
UT         False
Maths       True
Science     True
S.St       False
Hindi      False
Eng         True
dtype: bool

In [68]:
print(df['Science'].isnull().any())

True

Write a program to find the percentage of
marks scored by Raman in hindi.

In [69]:
dfRaman = df[df['Name']=='Raman']
print('Marks Scored by Raman:',dfRaman,sep="\n")

Marks Scored by Raman:
    Name  UT  Maths  Science  S.St  Hindi   Eng
0  Raman   1   22.0     21.0    18     20  21.0
1  Raman   2   21.0     20.0    17     22  24.0
2  Raman   3   14.0     19.0    15     24  23.0
3  Raman   4    NaN      NaN    19     18   NaN

In [70]:
dfHindi = dfRaman['Hindi']
print("Marks Scored by Raman in Hindi",dfHindi,sep="\n")

Marks Scored by Raman in Hindi
0    20
1    22
2    24
3    18
Name: Hindi, dtype: int64

In [71]:
row = len(dfHindi) # Number of Unit Tests held. Here row will be 4

Dropping Missing Values

In [72]:
df1 = df.dropna()
print(df1)

       Name  UT  Maths  Science  S.St  Hindi   Eng
0     Raman   1   22.0     21.0    18     20  21.0
1     Raman   2   21.0     20.0    17     22  24.0
2     Raman   3   14.0     19.0    15     24  23.0
4   Zuhaire   1   20.0     17.0    22     24  19.0
5   Zuhaire   2   23.0     15.0    21     25  15.0
6   Zuhaire   3   22.0     18.0    19     23  13.0
7   Zuhaire   4   19.0     20.0    17     21  16.0
8   Ashravy   1   23.0     19.0    20     15  22.0
9   Ashravy   2   24.0     22.0    24     17  21.0
10  Ashravy   3   12.0     25.0    19     21  23.0
11  Ashravy   4   15.0     20.0    20     20  17.0
12   Mishti   1   15.0     22.0    25     22  22.0
13   Mishti   2   18.0     21.0    25     24  23.0
14   Mishti   3   17.0     18.0    20     25  20.0
15   Mishti   4   14.0     20.0    19     20  18.0

In [73]:
# marks obtained by Raman in all the unit tests
dfRaman=df[df.Name=='Raman']
# inplace=true makes changes in the #original DataFrame i.e. dfRaman #here
dfRaman.dropna(inplace=True,how='any')
dfMaths = dfRaman['Maths'] # get the marks scored in Maths
print("\nMarks Scored by Raman in Maths",dfMaths,sep="\n")

Marks Scored by Raman in Maths
0    22.0
1    21.0
2    14.0
Name: Maths, dtype: float64

/tmp/ipykernel_1083/3619255146.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfRaman.dropna(inplace=True,how='any')

In [75]:
dfRaman = df.loc[df['Name']=='Raman']
dfScience = dfRaman.loc[:,'Science']
print("Marks Scored by Raman in Science",dfScience,sep="\n")

Marks Scored by Raman in Science
0    21.0
1    20.0
2    19.0
3     NaN
Name: Science, dtype: float64

In [76]:
dfFillZeroScience = dfScience.fillna(0)
print('Marks Scored by Raman in Science with Missing Values Replaced with  Zero',dfFillZeroScience,sep="\n")

Marks Scored by Raman in Science with Missing Values Replaced with  Zero
0    21.0
1    20.0
2    19.0
3     0.0
Name: Science, dtype: float64

In [77]:
dfEng = dfRaman.loc[:,'Eng']
print("Marks Scored by Raman in English",dfEng,sep="\n")

Marks Scored by Raman in English
0    21.0
1    24.0
2    23.0
3     NaN
Name: Eng, dtype: float64

`df.fillna(method='pad')` replaces the missing
value by the value before the missing value while
`df.fillna(method='bfill')` replaces the missing value by the
value after the missing value.

In [79]:
dfFillPadEng = dfEng.fillna(method='pad')
print('Marks Scored by Raman in English with Missing Values Replaced by Previous Test Marks',dfFillPadEng,sep="\n")

Marks Scored by Raman in English with Missing Values Replaced by Previous Test Marks
0    21.0
1    24.0
2    23.0
3    23.0
Name: Eng, dtype: float64

/tmp/ipykernel_1083/1245501210.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfFillPadEng = dfEng.fillna(method='pad')

## DataFrame Concatenation

In [84]:
df1 = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [25, 30]})
df2 = pd.DataFrame({'Name': ['Charlie', 'Dave'], 'Age': [35, 40]})
print(df1)
print(df2)
# Stack vertically (default is axis=0)
result = pd.concat([df1, df2])
print("Result of vertical concatenation")
print(result)

    Name  Age
0  Alice   25
1    Bob   30
      Name  Age
0  Charlie   35
1     Dave   40
Result of vertical concatenation
      Name  Age
0    Alice   25
1      Bob   30
0  Charlie   35
1     Dave   40

Note: By default, the original indexes are preserved. If you want a fresh sequential index in your output, use the `ignore_index=True` parameter:

In [81]:
result = pd.concat([df1, df2], ignore_index=True)
print(result)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3     Dave   40

In [85]:
# Join side-by-side
result = pd.concat([df1, df2], axis=1)
print("Result of Horizontal concatenation")
print(result)

Result of Horizontal concatenation
    Name  Age     Name  Age
0  Alice   25  Charlie   35
1    Bob   30     Dave   40